<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="DatabaseRecord" Id="{08677c20-da58-40c4-913e-93c21a52392f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM DatabaseRecord
VAR
	fbInfluxDBRecorder: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Database Writing actions
GVL.fbInfluxDBRecorder();
]]></ST>
    </Implementation>
    <LineIds Name="DatabaseRecord">
      <LineId Id="9" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>