<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="DbWriteInfluxDB" Id="{b3c9b1c0-8e19-46d8-955e-27b35c8007f9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM DbWriteInfluxDB
VAR
	// Cycle record data
	fbInfluxDBRecorder	:RecordInfluxDB;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Insert DB
fbInfluxDBRecorder(
	command_queue := GVL.tsdb_command_queue,
	nDBID := 1      // Database ID by TF6420 configurator
);
]]></ST>
    </Implementation>
    <LineIds Name="DbWriteInfluxDB">
      <LineId Id="36" Count="4" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>